name: Update Notebook Rendering

on:
  push:
    branches: [ main ]
    paths: 
      - '*.ipynb'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        pip install nbconvert jupyter
        
    - name: Clear notebook outputs (for better GitHub display)
      run: |
        jupyter nbconvert --clear-output --inplace *.ipynb
        
    - name: Commit cleared notebooks
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add *.ipynb
        git diff --staged --quiet || git commit -m "Clear notebook outputs for better GitHub display"
        git push